Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false
